apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: siem-ltm
  labels:
    app.kubernetes.io/name: grafana
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki:3100
        isDefault: false

