apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: siem-ltm
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      # Node Exporter (Kubernetes SD)
      - job_name: "node_exporter"
        static_configs:
          - targets: ['node-exporter.siem-ltm.svc.cluster.local:9100']

      # Endpoint Exporter (static)
      - job_name: "endpoint_exporter"
        static_configs:
          - targets: ["endpoint-exporter.siem-ltm.svc.cluster.local:9101"]

      # USB Exporter (static, empty)
      - job_name: "usb_exporter"
        static_configs:
          - targets: []

