apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: siem-event
data:
  telegraf.conf: |-
    [global_tags]
      cluster = "minikube"

    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      flush_interval = "10s"

    [[outputs.influxdb]]
      urls = ["http://influxdb.siem-event.svc.cluster.local:8086"]
      database = "system_metrics"

    [[inputs.cpu]]
      percpu = true
      totalcpu = true

    [[inputs.mem]]

    [[inputs.disk]]
      ignore_fs = ["tmpfs","devtmpfs"]

    [[inputs.net]]
      interfaces = ["eth0"]

    # USB tail input disabled
    #    [[inputs.tail]]
    #      from_beginning = true
    #      data_format = "influx"

